# Generated by Django 2.0.1 on 2019-07-11 09:42

import base_user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0003_myuser_is_completed'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', base_user.models.MyUserManager()),
            ],
        ),
    ]
