# Generated by Django 2.0.1 on 2019-07-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190628_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wish', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='published',
            field=models.BooleanField(default=False, verbose_name='published'),
        ),
    ]
