# Generated by Django 2.0.1 on 2019-07-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='short_link_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
