# Generated by Django 2.0.1 on 2019-07-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_wish_short_link_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
