# Generated by Django 2.0.1 on 2019-07-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190716_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='slug',
        ),
    ]
