# Generated by Django 2.0.1 on 2019-07-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_wish_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='short_link_name',
            new_name='slug',
        ),
    ]
