# Generated by Django 2.0.1 on 2019-07-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='identification_card_image',
            field=models.ImageField(null=True, upload_to='identification_card_image'),
        ),
    ]
